main.o: main.cpp classifier.cpp
	g++ -g -std=c++0x -Wall main.cpp classifier.cpp -o main

test.o: test.cpp classifier.cpp
	g++ -g -std=c++0x -Wall test.cpp classifier.cpp -o test

clean:
	rm -rf main test